modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="removegeodos"
version="1.0.0"
displayName="Remove Geodos"
authors="Gabriel"
description="Remove all amethyst geodes from the world."

[[dependencies.removegeodos]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.removegeodos]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"